sigstore/root-signing-staging

.github/dependabot.yml, .github/workflows/create-signing-events.yml, .github/workflows/online-sign.yml, .github/workflows/publish.yml, .github/workflows/signing-event.yml, README.md
Setup a tuf-on-ci running repository
* Copy workflows from tuf-on-ci-template
* Make sigstore specific tweaks to publishing paths in the workflows
* Add a barebones README
I kind of suspect these workflows won't work quite out of the box (as in the repository settings may need tweaking) but I think this is the way to find out
=> Add workflows

.github/workflows/publish.yml
This reverts commit 4de5f40af7b0aa54866167bd9e59003a28e870a9.
* as the release notes mentioned this requires actions/upload-pages-artifact@v3: tuf-on-ci does not use that yet
* The release also broke the whole Pages deploy pipeline: v4 does not seem to work anywhere right now
upload-pages-artifact can be upgraded with tuf-on-ci 0.4 (the next release).
=> Revert "build(deps): bump actions/deploy-pages from 3.0.1 to 4.0.0"

.github/workflows/create-signing-events.yml, .github/workflows/online-sign.yml, .github/workflows/publish.yml, .github/workflows/signing-event.yml
Upgrade to tuf-on-ci 0.4 RC to get
* custom token support
* support for deploy-pages v4
This is going to be a final test for tuf-on-ci 0.4 (since the custom
token support is pretty much impossible to finally test without a GitHub
org that is sufficiently locked down).
* If everything works out we release tuf-on-ci 0.4 as is
* Then root-signing-staging upgrades to real tuf-on-ci 0.4
=> workflows: Upgrade to tuf-on-ci 0.4 Release Candidate

.github/workflows/create-signing-events.yml, .github/workflows/online-sign.yml, .github/workflows/publish.yml, .github/workflows/signing-event.yml
This is a really minor bump as we were on the release candidate already.
Also make a few whitespace tweaks to make sure the workflows match the ones in tuf-on-ci-template: now the "diff" from there shows only the added metadata_path argument to upload_repository.
Closes #1
=> Upgrade tuf-on-ci actions to 0.4.0

.github/workflows/create-signing-events.yml, .github/workflows/online-sign.yml, .github/workflows/publish.yml, .github/workflows/signing-event.yml, .github/workflows/test.yml
Upgrade to tuf-on-ci 0.5
These workflow changes come from tuf-on-ci-template: https://github.com/theupdateframework/tuf-on-ci-template/:
* New job in each workflow to file issues if a workflow fails
* New reusable workflow to run smoke tests
* called on schedule
* called during publish
--- 
I had planned to add a sigstore client test in this same PR  (see #32) but it requires some test runs  and I can't do those before the test workflow is in main. The test workflow is useful already as it tests that the repository is a working TUF repository
=> Workflows: Upgrade to tuf-on-ci 0.5

.github/workflows/test.yml
Tweaks to the smoke test that was added yesterday.
* a missed configuration change for root-signing publishing directory structure
* a bug in tuf-on-ci-template: It's annoying that we have to resort to workflow name matching but it seems to be the only possibility without significantly more complex code (the purpose of the condition is to avoid filing an issue in both calling workflow and this workflow during `workflow_call`)
Fixes #36 .
=> workflows: Fix the smoke test

.github/workflows/custom-test.yml, .github/workflows/test.yml
workflows: Add a smoke test that uses a sigstore client 
This makes sure that the repository we have published to Pages works as a Sigstore Staging root-signing repository:
* installs sigstore-python
* modifies sources to use our TUF URL (this is not yet exposed in sigstore-python CLI)
* runs sign & verify: sigstore-python will update metadata from our published TUF repository
This does not actually check that the client has received the expected metadata versions but the tuf-on-ci test has already tested that the published repository versions match expected versions.
Fixes #32
=> workflows: Add a custom test workflow

.github/workflows/custom-test.yml
I don't think testing loads of clients (in this repository) is a good idea but
* cosign is important
* cosign does not use sigstore-conformance so even adding staging tests there won't help
So let's test cosign right here, at least for now
=> workflows: Add a custom smoke test with cosign

.github/workflows/deploy-to-gcs.yml, .github/workflows/publish.yml
Fixes #7
This uploads the repository to GCS and invalidates the CDN cache.
* the workflow is a custom one for root-signing
* it is called as a reusable workflow from the TUF-on-CI publish workflow (so gets automated issue failing on errors)
GCP configuration is mostly hard coded, only service account details are inputs:
* service account: same as online signing
* project: projectsigstore-staging
* GCS bucket: tuf-root-staging
* CDN load balancer: tuf-repo-cdn-lb
=> Add a GCS deploy workflow

.github/workflows/custom-test.yml, .github/workflows/publish.yml, .github/workflows/test-gcs.yml, .github/workflows/test.yml
* We already test the GH Pages-published repo before the "real publish" to GCS
* We also want to test the GCS-published repo
* We especially want to test the GCS repo once #68 makes GCS upload more complicated
This PR implements tests for GCS published repo. Fixes #53.
This likely makes sense to merge before #68: This isn't really testable outside the repo so we'll need to merge and then test by:
* first manually dispatching online-sign -- this will dispatch publish and all tests
* then manually dispatching test-gcs.yml
1. Parametrize `custom-test` so that it can be used to test any URL.
1. Make an almost exact copy of `test`: The only difference is that `test-gcs` runs all tests against GCS and not GH Pages (this is not parametrized as we want to run these on schedule: it's unfortunately …
=> Add tests for GCS publish

.github/workflows/custom-test.yml, .github/workflows/test-gcs.yml
Fixes #71:
```
Error from called workflow sigstore/root-signing-staging/.github/workflows/custom-test.yml@185af8249bc4833c316af83a0f4fdb594805fc07 (Line: 7, Col: 9):
Required property is missing: type
```
Verifying changes around the testing is quite a lot of work so the original change and  this fix have not been tested in a running repository: If there are further issues with the actual test I will likely do the work of testing outside of root-signing-staging but this one seems simple enough to just yolo (the alternative is to revert #70 and try again later)
=> workflows: Set missing input type

.github/PULL_REQUEST_TEMPLATE/signing_event.md
The next signing tool release will try to use this template when non-maintainer signers submit their signatures.
---
Suggestions on the contents are welcome:
* its a bit vague since we don't really know if this is a signature or adding a key
* the main value is that we can add project specific info here like maintainer names (or potentially include whatever terms will trigger slack integration etc)
My plan is to release new tuf-on-ci as soon as theupdateframework/tuf-on-ci#209 is merged, and then start handling #74 here. If we have merged this before doing #74 we should see this template being used there.
=> Add a signing event PR template

.github/workflows/deploy-to-gcs.yml
* Negative caching is now disabled on staging: see https://github.com/sigstore/public-good-instance/pull/2167
* This means that both the 404 root request and the timestamp.json request that clients make are uncached and come from GCS
* Assumption is that this fixes #84 and test-repository action should now succeed immediately after deployment
* The production (sigstore-prober) failures in September 2023 are still unexplained but we want to test this setup in staging
=> workflows: Remove cache invalidation from GCS deploy

.github/workflows/test-gcs.yml, .github/workflows/test.yml
Use three new features of test-repository:
* update_base_url
During publish workflow we want to test that a client can update from current GCS (tuf-repo.cdn.sigstage.dev) to Pages
(sigstore.github.io/root-signing-staging/).
This test is done during cron runs as well but then it's usually not relevant (as the repos contents typically match).
* valid_days
We want a failure if either Pages or GCS repository is invalid in 3 days.
Note: sigstore-probers alerts when repository is invalid in 2 days
* offline_valid_days
We want a failure if root or targets in either Pages or GCS repository expires within 30 days.
Note: sigstore-probers alerts when offline roles expire in 15 days
--- 
Fixes #94 
I have test runs: 
* [test.yml](https://github.com/jku/root-signing-staging/actions/runs/8615129850/job/ …
=> workflows: Use new test-repository features

.github/workflows/custom-test.yml
This is part of #79. Fixes #91.
* I'm not super happy about making the custom-test.yml longer and more complicated but we can try this
* I don't know what the correct method of installing go apps is but this seems to work?
=> workflows: Add test for sigstore-go

.github/workflows/custom-test.yml
Publish workflow wants to call custom-test reusable workflow twice. This currently fails because both runs want to upload artifact 'bundle'.
We don't really care about the specific artifact so can just allow overwriting.
Fixes #102
--- 
This issue appeared from #99 (which started uploading the artifact for new client tests)
=> workflows: Make sure custom-test.yml can run twice

.github/workflows/custom-test.yml
Sigstore-python default bundle name changed in 3.0:
* Switch to using the new default
* Specify the name anyway to prevent issues in future
Fixes #120. Fixes #121.
=> workflows: In custom test specify bundle name

.github/workflows/custom-test.yml
Add sigstore-java to the custom client tests:
* Use the new `--staging-with-tuf-url-override` flag
* The CLI used here is not a real application but a testing tool so we need to build it from source: try to checkout the latest release tag to do that
For context, I'm not 100% convinced root-signing* _should_ test all possible clients in the future... but for the production tuf-on-ci migration a test matrix as large as possible seems like good idea.
=> Add sigstore-java to the test set

.github/workflows/custom-test.yml
* sigstore-java cannot handle the hashes we use
* Disable the test to allow the publish to proceed: this breaks sigstore-java on staging but the client fix should be easy
#161 -- plan is to not do this (modify artifacts so that it leads to hash changes) in production in near future, but instead evaluate situation again after sigstore-java has been fixed
=> Disable sigstore-java test temporarily

.github/workflows/test-gcs.yml, .github/workflows/test.yml
currently the signing periods are 32 days.
If we require metadata to to be valid for 30 days, then there is only 2 days signing time before there is a test failure.
Lower this to 16 days: That way we get a test failure if the signing has not happened in half the signing period -- this is still good to have in case of e.g. signing event creation failure.
See #177 for an example
=> tests: Lower the required validity time

.github/workflows/custom-test.yml
It would be nice to have full matrix of clients and versions but maintainer resources are limited... so let's just add an older version of the most used client.
Fixes #172
=> client tests: Test with an older cosign

.github/workflows/test-gcs.yml, .github/workflows/test.yml
Tests can currently prevent publish from failing if the metadata is valid but just short lived: We do not want that, especially we do not want timestamp/snapshot updates being blocked because root will expire in 3 weeks.
Make sure the future validity checks are not done when reusing test.yml/test-gcs.yml workflow from publish.yml. Publish still makes sure the repository is valid and passes all client tests.
---
Fixes the underlying issue for #177
=> Workflows: Make sure publish does not fail easily

.github/workflows/test-gcs.yml, .github/workflows/test.yml
This combines two related changes:
* Fix #216: currently publishing requires validity in the future because of a bug: we do not want that since it creates tricky situations where some metadata cannot be updated if another metadata is expiring soon. The fix is a bit hacky but seems to work.
* Extend the required validity time for online signatures (timestamp) from 3 days to 5. This is https://github.com/sigstore/root-signing/issues/1415 and is useful since it gives us more time to react to issues with online signing
More details in commit messages for those interested.
=> Extend timestamp validity check

.github/workflows/custom-test.yml
This is a temporary fix to stop tests from failing until there is an actual solution for
https://github.com/sigstore/root-signing/issues/1542
I'll trigger the tests manually -- that likely closes the automatically opened issues for now but they will be reopened until this is merged.
=> tests: Pin sigstore-python for now
